# Generated by Django 5.1.15 on 2026-07-24 19:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0002_supplier_consentrecord_dischargesummary_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ambulance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_number", models.CharField(max_length=30, unique=True)),
                ("driver_name", models.CharField(max_length=150)),
                ("driver_phone", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("DISPATCHED", "Dispatched"),
                            ("MAINTENANCE", "Maintenance"),
                        ],
                        db_index=True,
                        default="AVAILABLE",
                        max_length=15,
                    ),
                ),
                ("last_known_location", models.CharField(blank=True, max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="BloodDonor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("blood_group", models.CharField(db_index=True, max_length=5)),
                ("phone", models.CharField(max_length=20, unique=True)),
                ("date_of_birth", models.DateField()),
                ("address", models.TextField(blank=True)),
                ("last_donation_date", models.DateField(blank=True, null=True)),
                ("is_eligible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BloodRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blood_group", models.CharField(max_length=5)),
                ("component", models.CharField(default="Whole Blood", max_length=50)),
                (
                    "units_required",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Routine"),
                            ("URGENT", "Urgent"),
                            ("EMERGENCY", "Emergency"),
                        ],
                        default="ROUTINE",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("RESERVED", "Reserved"),
                            ("ISSUED", "Issued"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="REQUESTED",
                        max_length=12,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hospital.patient",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BloodUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_number", models.CharField(max_length=50, unique=True)),
                ("blood_group", models.CharField(db_index=True, max_length=5)),
                ("component", models.CharField(default="Whole Blood", max_length=50)),
                ("collection_date", models.DateField()),
                ("expiry_date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("RESERVED", "Reserved"),
                            ("ISSUED", "Issued"),
                            ("EXPIRED", "Expired"),
                            ("DISCARDED", "Discarded"),
                        ],
                        db_index=True,
                        default="AVAILABLE",
                        max_length=12,
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.blooddonor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmergencyCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "temporary_patient_name",
                    models.CharField(blank=True, max_length=150),
                ),
                ("arrival_time", models.DateTimeField(auto_now_add=True)),
                (
                    "triage_level",
                    models.CharField(
                        choices=[
                            ("RED", "Red - immediate"),
                            ("YELLOW", "Yellow - urgent"),
                            ("GREEN", "Green - non-urgent"),
                            ("BLACK", "Black - deceased"),
                        ],
                        db_index=True,
                        default="YELLOW",
                        max_length=10,
                    ),
                ),
                ("chief_complaint", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ARRIVED", "Arrived"),
                            ("TRIAGED", "Triaged"),
                            ("ADMITTED", "Admitted"),
                            ("DISCHARGED", "Discharged"),
                            ("REFERRED", "Referred"),
                        ],
                        db_index=True,
                        default="ARRIVED",
                        max_length=12,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "assigned_doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emergency_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AmbulanceDispatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pickup_location", models.TextField()),
                ("contact_phone", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DISPATCHED", "Dispatched"),
                            ("PICKED_UP", "Patient picked up"),
                            ("ARRIVED", "Arrived at hospital"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DISPATCHED",
                        max_length=15,
                    ),
                ),
                ("dispatched_at", models.DateTimeField(auto_now_add=True)),
                ("arrived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ambulance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispatches",
                        to="hospital.ambulance",
                    ),
                ),
                (
                    "emergency_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.emergencycase",
                    ),
                ),
            ],
        ),
    ]
